name: RedstoneCircuitManager
version: '${project.version}'
main: org.jajader.RedstoneCircuitManager
api-version: '1.20'
commands:
  load:
    description: r
  save:
    description: n
  pos1:
    description: r
  pos2:
    description: n
